export const GET_INCOMING_DATA_REQUEST = 'charts/GET_INCOMING_DATA_REQUEST';
export const GET_INCOMING_DATA_SUCCESS = 'charts/GET_INCOMING_DATA_SUCCESS';
export const GET_INCOMING_DATA_ERROR = 'charts/GET_INCOMING_DATA_ERROR';
export const TOGGLE_CHART = 'charts/TOGGLE_CHART';
export const SHOW_ALL_CHARTS = 'charts/SHOW_ALL_CHARTS';
export const HIDE_ALL_CHARTS = 'charts/HIDE_ALL_CHARTS';
